name: "Pull Request Docs Check"
on: 
- pull_request
- push

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: ls -al
    - uses: actions/checkout@v3
      with:
        repository: Sungmo-OSS-Project/txt_game_prototype
        path: 'repo'
    - run: ls -al repo
    - uses: ammaraskar/sphinx-action@master
      with:
        pre-build-command: "pip install sphinx_rtd_theme"
        docs-folder: "docs/"
    - run: tree -a